spring:
  data-source:
    url: jdbc:sqlserver://localhost:1433;databaseName=SportsStoreTest;integratedSecurity=true;trustServerCertificate=true
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

